src/utils/models.py
from passlib.hash import pbkdf2_sha512


class Utils(object):

    @staticmethod
    def set_password(password):
        return pbkdf2_sha512.encrypt(password)

    @staticmethod
    def check_password(pw_hashed, password):
        return pbkdf2_sha512.verify(password, pw_hashed)

src/__init__.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager

from config import config
from src.utils.models import Utils
from src.users.models import User


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    login_manager.init_app(app)

    from src.auth import bp_auth
    app.register_blueprint(bp_auth, url_prefix='/auth')

    from src.users import bp_user
    app.register_blueprint(bp_user, url_prefix='/users')

    from src.posts import bp_post
    app.register_blueprint(bp_post, url_prefix='/posts')

    from src.admin import bp_admin
    app.register_blueprint(bp_admin, url_prefix='/admin')

    from src.messages import bp_message
    app.register_blueprint(bp_message, url_prefix='/messages')

    @app.route('/')
    def index():
        return render_template('index.html')

    from config import Admin as ADMINS
    from src.admin.models import Admin

    @app.before_first_request
    def init_admin():
        admin1 = Admin(name=ADMINS.ADMIN_1[0]['name'],
                       family=ADMINS.ADMIN_1[0]['family'],
                       email=ADMINS.ADMIN_1[0]['email'],
                       password=Utils.set_password(ADMINS.ADMIN_1[0]['password']),
                       permission=ADMINS.ADMIN_1[0]['permission']
                       )

        admin2 = Admin(name=ADMINS.ADMIN_2[0]['name'],
                       family=ADMINS.ADMIN_2[0]['family'],
                       email=ADMINS.ADMIN_2[0]['email'],
                       password=Utils.set_password(ADMINS.ADMIN_2[0]['password']),
                       permission=ADMINS.ADMIN_2[0]['permission']
                       )

        admin1.init_neo4j()
        admin2.init_neo4j()

    @login_manager.user_loader
    def user_loader(user_id):
        if user_id is None:
            return redirect(url_for("auth.login"))

        user = User.find_by_id(user_id)
        admin_data = Admin.find_admin_id(user_id)
        if admin_data:
            admin = Admin.classify(name=admin_data["name"],
                                   family=admin_data["family"],
                                   email=admin_data["email"],
                                   password=admin_data["password"],
                                   permission=admin_data["permission"],
                                   _id=admin_data["_id"])
            return admin
        if user:
            return user

    return app

src/admin/__init__.py
from flask import Blueprint


bp_admin = Blueprint('admins', __name__)

from . import views

src/admin/views.py
from flask import render_template, flash, request, redirect, url_for, session, g
from flask_login import current_user, logout_user

from . import bp_admin
from src.users.models import User
from src.posts.models import Post
from src.admin.models import Admin


@bp_admin.route('/home')
def admin_home():
    posts = Post.admin_sent_posts()
    if posts:
        return render_template('admin/home.html', posts=posts, admin_email=current_user.email)
    return render_template('admin/home.html', admin_email=current_user.email)


@bp_admin.route('/posts_sent/edit/<string:post_id>', methods=['GET', 'POST'])
def admin_posts_edit(post_id):
    post = Post.find_one(post_id)

    if request.method == 'POST':
        title = request.form["title"]
        content = request.form["content"]
        Post.admin_sent_posts_edit(post_id, title, content)
        return redirect(url_for('admins.admin_home'))

    request.form.title = post["subject"]
    request.form.content = post["content"]

    return render_template("admin/edit.html")


@bp_admin.route('/posts_sent/delete/<string:post_id>')
def admin_posts_delete(post_id):
    Post.admin_sent_posts_delete(post_id)
    flash("Post DELETED")
    return redirect(url_for('admins.admin_home'))


@bp_admin.route('/users', methods=['GET', 'POST'])
def admin_users():
    search = True
    msg = None
    if request.method == 'POST':
        word = request.form["search"].strip().lower()
        if word.isdigit():
            users = []
            user = User.find_one(word)
            if user:
                user = User.classify1(user)
                users.append(user)
                return render_template("admin/users.html", users=users,
                                       search=search, msg=msg, activate="active")
            else:
                msg = "Not found any user by {0}".format(word)
                return render_template("admin/users.html",
                                       search=search, msg=msg, activate="active", nothing=True)

        elif word.isalpha() and '@' not in word:
            if " " in word:
                name_family = word.split(" ")
                if len(name_family) == 2:
                    name, family = name_family
                    users = User.search_by_name_family(name=name, family=family)
                    if users:
                        return render_template("admin/users.html", users=users,
                                               search=search, msg=msg, activate="active")
                    else:
                        msg = "Not found any user by {0}".format(word)
                        return render_template("admin/users.html",
                                               search=search, msg=msg, activate="active", nothing=True)

                elif len(name_family) == 3:
                    name, mid_name, family = name_family
                    users1 = User.search_by_name_family(name=name + " " + mid_name, family=family)
                    users2 = User.search_by_name_family(name=name, family=mid_name + " " + family)
                    users = users1 + users2
                    if users:
                        return render_template("admin/users.html", users=users,
                                               search=search, msg=msg, activate="active")
                    else:
                        msg = "Not found any user by {0}".format(word)
                        return render_template("admin/users.html",
                                               search=search, msg=msg, activate="active", nothing=True)

            elif " " not in word:
                users = User.search_by_name_family(name=word, family=word)
                if users:
                    return render_template("admin/users.html", users=users,
                                           search=search, msg=msg, activate="active")
                else:
                    msg = "Not found any user by {0}".format(word)
                    return render_template("admin/users.html",
                                           search=search, msg=msg, activate="active", nothing=True)

        elif '@' in word:
            users = []
            users.append(User.find_by_email(word))
            if users:
                return render_template("admin/users.html", users=users,
                                       search=search, msg=msg, activate="active")
            else:
                msg = "Not found any user by {0}".format(word)
                return render_template("admin/users.html",
                                       search=search, msg=msg, activate="active", nothing=True)

        else:
            msg = "Not found any user by {0}".format(word)
            return render_template("admin/users.html",
                                   search=search, msg=msg, activate="active", nothing=True)

    return render_template("admin/users.html", search=search, msg=msg, activate="active", nothing=True)


@bp_admin.route('/show_all_users')
def show_all_users():
    users = Admin.find_all_users()
    return render_template('admin/users.html', users=users,
                           search=False, msg=None, activate="active")


@bp_admin.route('/posts', methods=['GET', 'POST'])
def admin_posts():
    search = True
    msg = None
    if request.method == 'POST':
        if request.form["search"]:
            word = request.form["search"].strip()
            option = request.form["radio"]

            if option == 'author':
                user = User.find_by_email(word)
                if not user:
                    msg = "There is no user by this email: {0}".format(word)
                    return render_template("admin/posts.html", activate='active', search=search, msg=msg)
                posts = Post.admin_find_posts_by_author(word)
                if posts:
                    search = None
                    return render_template("admin/posts.html",
                                           activate='active',
                                           search=search,
                                           msg=msg,
                                           posts=posts)
                else:
                    msg = "There is no post by this author: {0}".format(word)
                    return render_template("admin/posts.html", activate='active', search=search, msg=msg)

            elif option == 'date':
                if '-' in word:
                    date = word.split('-')
                    if len(date) >= 2:
                        posts = Post.admin_find_posts_by_date(*date)
                        search = None
                        return render_template("admin/posts.html",
                                               activate='active',
                                               search=search,
                                               msg=msg,
                                               posts=posts)
                elif word.isdigit():
                    date = [word]
                    posts = Post.admin_find_posts_by_date(*date)
                    search = None
                    return render_template("admin/posts.html",
                                           activate='active',
                                           search=search,
                                           msg=msg,
                                           posts=posts)

                else:
                    msg = "There is no post in this date: {0}\n Date format should be YEAR-MONTH-DAY-HOUR".format(word)
                    return render_template("admin/posts.html", activate='active', search=search, msg=msg)

            elif option == 'title':
                if ' ' in word:
                    word = word.split(' ')
                    posts = Post.admin_find_posts_by_title(*word)
                    if posts:
                        search = None
                        return render_template("admin/posts.html",
                                               activate='active',
                                               search=search,
                                               msg=msg,
                                               posts=posts)

                    else:
                        msg = "There is no post by this title: {0}".format(word)
                        return render_template("admin/posts.html", activate='active', search=search, msg=msg)

                elif ' ' not in word:
                    word = [word]
                    posts = Post.admin_find_posts_by_title(*word)
                    if posts:
                        search = None
                        return render_template("admin/posts.html",
                                               activate='active',
                                               search=search,
                                               msg=msg,
                                               posts=posts)

                    else:
                        msg = "There is no post by this title: {0}".format(word)
                        return render_template("admin/posts.html", activate='active', search=search, msg=msg)

            elif option == 'content':
                if ' ' in word:
                    words = word.split(' ')
                    posts = Post.admin_find_posts_by_content(*words)
                    if posts:
                        search = None
                        return render_template("admin/posts.html",
                                               activate='active',
                                               search=search,
                                               msg=msg,
                                               posts=posts)

                    else:
                        msg = "There is no post by this content: {0}".format(word)
                        return render_template("admin/posts.html", activate='active', search=search, msg=msg)

                elif ' ' not in word:

src/app.py
from flask import render_template, redirect, url_for

from src import create_app, login_manager
from src.users.models import User
from src.admin.models import Admin

src/common/__init__.py
from flask import Blueprint


bp_common = Blueprint('common', __name__)

from . import views

src/common/views.py
from flask import redirect,url_for
from . import bp_common
from flask_login import login_required,current_user


@bp_common.route('/home/')
@login_required
def home():
    return 'here is home'


@bp_common.route('/login/')
def login():
    return redirect(url_for('auth.login'))

src/messages/__init__.py
from flask import Blueprint


bp_message = Blueprint('messages', __name__)

from . import views

src/messages/views.py
from flask import redirect, request, url_for, flash, render_template
from flask_login import login_required, current_user

from . import bp_message
from src.posts.models import Post
from src.users.models import User
from src.messages.forms import NewMessage


@bp_message.route('/new', methods=['GET', 'POST'])
@login_required
def new_post_pv():
    form = NewMessage()
    if request.method == 'POST':
        subject = form.subject.data
        to = form.to.data
        content = form.content.data

        if to.isalnum():
            user = User.find_one(to)
            user_email = user["email"]
        else:
            user = User.find_by_email(to)
            user_email = user["email"]

        if user_email:
            Post(user_email=current_user.email,
                 subject=subject,
                 content=content,
                 type_publication="private").insert_by_type(to=user_email,
                                                            user_email=user_email,
                                                            _type='private')

            user = User.find_by_email(current_user.email)
            flash("Message sent to {0}".format(to))
            return redirect(url_for('messages.inbox', user_id=user["_id"]))

        flash("There is no user with this email or phone number.")
        return redirect(url_for('messages.new_post_pv'))

    return render_template("message/new_pv.html", form=form)


@bp_message.route('/replay/<string:author>', methods=['GET', 'POST'])
@login_required
def replay(author):
    form = NewMessage()
    if request.method == 'POST':
        subject = form.subject.data
        content = form.content.data
        to = form.to.data

        if to.isalnum():
            user = User.find_one(to)
            user_email = user["email"]
        else:
            user = User.find_by_email(to)
            user_email = user["email"]

        if user and user_email != current_user.email:
            Post(user_email=current_user.email,
                 subject=subject,
                 content=content,
                 type_publication="private").insert_by_type(to=user_email, user_email=user_email)

            user = User.find_by_email(current_user.email)
            flash("Message sent to {0}".format(to))
            return redirect(url_for('posts.inbox', user_id=user["_id"]))

        else:
            flash("Wrong user.")
            return redirect(url_for('messages.inbox', user_id=user["_id"]))

    form.to.data = author
    return render_template("message/new_pv.html", form=form)


@bp_message.route('/inbox')
@login_required
def inbox():
    posts = Post.find_message(current_user.email)

    return render_template("message/inbox.html", posts=posts)


@bp_message.route('/inbox/delete/<string:post_id>')
@login_required
def delete_message_inbox(post_id):
    user = User.find_by_email(current_user.email)
    if Post.delete_message_inbox(post_id, user):
        flash("Message deleted.")
    return redirect(url_for('messages.inbox'))


@bp_message.route('/outbox/delete/<string:post_id>')
@login_required
def delete_message_outbox(post_id):
    user = User.find_by_email(current_user.email)
    if Post.delete_message_inbox(post_id, user):
        flash("Message deleted.")
    return redirect(url_for('messages.outbox'))


@bp_message.route('/outbox')
def outbox():
    posts = Post.find_all_type(current_user.email, 'private')
    if posts:
        posts_length = len(posts)
    else:
        posts_length = 0
    return render_template('message/outbox.html', posts=posts, posts_length=posts_length)

src/payments/views.py
from flask import Blueprint

from src.users.models import User


bp_accounts = Blueprint('payments', __name__)


@bp_accounts.route('/new/<string:user_id>')
def new_account(user_id):
    # user = User.find_by_id(user_id)
    pass

src/posts/__init__.py
from flask import Blueprint


bp_post = Blueprint('posts', __name__)

from . import views

src/users/__init__.py
from flask import Blueprint


bp_user = Blueprint('users', __name__)

from . import views

src/templates/user/change_pw.html
{% extends "base.html" %}

{% block title %}
    Change Password
{% endblock %}

{% block article %}
    <article>
        <header>
            <h3>Change Password</h3>
        </header>
        <form method="POST">
            <ul>
                <li>
                    <section>
                        <div>
                            <p>{{ form.current_password.label }}</p>
                                {% if form.current_password.errors %}
                                    {% for error in form.current_password.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            <p>{{ form.current_password }}</p>
                        </div>
                    </section>
                </li>
                <li>
                    <section>
                        <div>
                            <p>{{ form.new_password.label }}</p>
                                {% if form.new_password.errors %}
                                    {% for error in form.new_password.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            <p>{{ form.new_password }}</p>
                        </div>
                    </section>
                </li>
                <li>
                    <section>
                        <div>
                            <p>{{ form.confirm_password.label }}</p>
                                {% if form.confirm_password.errors %}
                                    {% for error in form.confirm_password.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            <p>{{ form.confirm_password }}</p>
                        </div>
                    </section>
                </li>
            </ul>

            <button type="submit" class="btn btn-warning">Change password</button>
        </form>
    </article>
{% endblock %}

{% block aside %}

{% endblock %}

src/templates/user/home.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock %}

{% block header %}
    <div class="header-container">
        <header class="wrapper clearfix">
            <!-- TODO make this part work (WITHOUT SENDING USER_ID) -->
            {% if user_id %}<a href="{{ url_for('users.home') }}"><h1 class="title">Network Marketing</h1></a>
            {% else %}<a href="{{ url_for('index') }}"><h1 class="title">Network Marketing</h1></a>
            {% endif %}
            <nav>
                <ul>
                    {% if loged_in %}<li><a href="{{ url_for('auth.login') }}">Log in</a></li>{% endif %}
                    {% if loged_in %}<li><a href="{{ url_for('auth.register') }}">Register</a></li>{% endif %}
                    <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <div class="flash">
        <div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class=flashes>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

{% block article %}
    <article>
        <header>
            <h1>Hello {{ current.name }}</h1>
        </header>
        <div class="container">
            <a href="{{ url_for('messages.new_post_pv') }}"><button class="btn btn-success">New message</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('users.change_password') }}"><button class="btn btn-success">Change password</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.view_sent_posts', user_id=current._id) }}"><button class="btn btn-success">View sent posts</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.new_post') }}"><button class="btn btn-success">New post</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('messages.inbox') }}"><button class="btn btn-success">Inbox</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('messages.outbox') }}"><button class="btn btn-success">Outbox</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.view_public_posts') }}"><button class="btn btn-success">View public posts</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.posts_from_subsets') }}"><button class="btn btn-success">Posts from subsets</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.posts_from_uplines') }}"><button class="btn btn-success">Posts from uplines</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('posts.posts_for_directs') }}"><button class="btn btn-success">Posts for directs</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('users.view_profile', user_id=current._id) }}"><button class="btn btn-success">Personal info</button></a>
            <br>
        </div>
        <div class="container">
            <br>
            <a href="{{ url_for('users.feedback') }}"><button class="btn btn-success">FeedBack</button></a>
            <br>
        </div>
    </article>
{% endblock %}

{% block aside %}
    <aside>
        <br>
        <a href="{{ url_for('users.view_uplines') }}"><button class="btn btn-default">Uplines</button></a>
        <br>
        <br>
        <a href="{{ url_for('users.view_subsets') }}"><button class="btn btn-default">Subsets</button></a>
    </aside>
{% endblock %}

{% block footer %}
    <footer class="wrapper">
        <section>
            <form action="" method="POST">
                <div>
                    <label for="search"> Search
                        <br>
                        <span>
                            <input type="text" style="color: #0f0f0f" name="search" id="search" value="{{ request.form.search }}" placeholder="Emails, Names">
                            <button class="btn btn-default" type="submit">Search</button>
                        </span>
                    </label>
                </div>
            </form>
        </section>
        <br>
        <br>
        <br>
        <br>
    </footer>
{% endblock %}

src/templates/user/personal_page.html
{% extends "user/home.html" %}

{% block article %}
    <article>
        <div class="container">
            <h3><strong>{{ user.name }}</strong> profile</h3>
            <p><strong>Full name: </strong>{{ user.name }} {{ user.family }}</p>
            <p><strong>Gender: </strong>{{ user.gender }}</p>
            <p><strong>Company: </strong>{{ user.company }}</p>
            <p><strong>Register date: </strong>{{ user.register_date }}</p>
            <p><strong>Email: </strong>{{ user.email }}</p>
            <div class="container">
                <span>
                {% if current_user != user %}
                    <a href="{{ url_for('users.follow', user_id=user._id) }}"><button class="btn btn-info" type="button" id="follow" name="follow">{{ request.form.follow }}</button></a>
                {% endif %}
                {% if current_user == user %}
                    <a href="{{ url_for('users.edit_profile') }}"><button class="btn btn-info" type="button" id="follow" name="follow">Edit Profile</button></a>
                {% endif %}
                </span>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </article>
{% endblock %}

{% block aside %}
{% endblock %}

{% block footer %}
{% endblock %}

src/templates/user/profile.html
{% extends "base.html" %}

{% block title %}
    Profile
{% endblock %}

{% block header %}
    <div class="header-container">
        <header class="wrapper clearfix">
            <h1 class="title">Network Marketing</h1>
            <nav>
                <ul>
                    {% if loged_in %}<li><a href="{{ url_for('users.login') }}">Log in</a></li>{% endif %}
                    {% if loged_in %}<li><a href="{{ url_for('users.register') }}">Register</a></li>{% endif %}
                </ul>
            </nav>
        </header>
    </div>
    <div class="flash">
        <div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class=flashes>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

{% block article %}
    <article>
        <header>
            <h3>Profile Info</h3>
        </header>
        <section>
            <form method="POST">
                <ul>
                    <li>
                        <div>
                           <p>{% if form.name.data is not none %}{{ form.name.data }}{% endif %}</p>
                            <p>{{ form.name.label }}</p>
                            <p>{{ form.name }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>{% if form.family_name.data %}{{ form.family_name.data }}{% endif %}</p>
                            <p>{{ form.family_name.label }}</p>
                            <p>{{ form.family_name }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>{% if form.email.data %}{{ form.email.data }}{% endif %}</p>
                            <p>{{ form.email.label }}</p>
                            <p>{{ form.email }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>{{ form.company.label }}</p>
                            <p>{{ form.company }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>{{ form.gender.label }}</p>
                            <p>{{ form.gender }}</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <p>{% if form.birthday_day.data %}{{ form.birthday_day.data }}{% endif %}</p>
                            <p>{{ form.birthday_day.label }}</p>
                            <p>{{ form.birthday_day(onclick="PersianDatePicker.Show(this, '1370/03/22')") }}</p>
                        </div>
                    </li>

                </ul>

                <button type="submit" class="btn btn-success">Register</button>

            </form>
        </section>
    </article>
{% endblock %}

{% block aside %}

{% endblock %}

src/templates/user/result.html
{% extends "user/home.html" %}

{% block title %}
    Result
{% endblock %}

{% block header %}
    <div class="header-container">
        <header class="wrapper clearfix">
            {% if user_id %}<a href="{{ url_for('users.home') }}"><h1 class="title">Network Marketing</h1></a>
            {% else %}<a href="{{ url_for('index') }}"><h1 class="title">Network Marketing</h1></a>
            {% endif %}
            <nav>
                <ul>
                    {% if loged_in %}<li><a href="{{ url_for('auth.login') }}">Log in</a></li>{% endif %}
                    {% if loged_in %}<li><a href="{{ url_for('auth.register') }}">Register</a></li>{% endif %}
                    <li><a href="{{ url_for('users.home', user_id=user_id) }}">Home</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <div class="flash">
        <div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class=flashes>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

{% block article %}
    <article>
        <h4>Result: </h4>
        <div class="container">
            <br>
            {% if users %}
                {% for user in users %}
                    <p>Name: {{ user.name }}</p>
                    <p>Family: {{ user.family }}</p>
                    <p>Gender: {{ user.gender }}</p>
                    <p>Email: {{ user.email }}</p>
                    <hr>
                {% endfor %}
            {% else %}
                <p>Could not find anyone.</p>
            {% endif %}
        </div>
    </article>
{% endblock %}

{% block aside %}

{% endblock %}

{% block footer %}
    <footer class="wrapper">
    </footer>
{% endblock %}